services:

  dev:
    
    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      
    volumes:
      - /mnt/wslg:/mnt/wslg

    devices:
      - /dev/dxg:/dev/dxg
    
  app:

    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      
    volumes:
      - /mnt/wslg:/mnt/wslg

    devices:
      - /dev/dxg:/dev/dxg
