services:

  dev:
    
    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - LIBGL_ALWAYS_SOFTWARE=0
      - GALLIUM_DRIVER=d3d12
      
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl

    devices:
      - /dev/dxg:/dev/dxg
    
  app:

    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - LIBGL_ALWAYS_SOFTWARE=0
      - GALLIUM_DRIVER=d3d12
      
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl

    devices:
      - /dev/dxg:/dev/dxg
