services:

  dev:
    
    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      
    devices:
      - /dev/dri:/dev/dri

    group_add:
      - video
      - render
    
  app:
    
    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      
    devices:
      - /dev/dri:/dev/dri

    group_add:
      - video
      - render
