services:

  dev:
    
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      
    devices:
      - /dev/dri:/dev/dri

    group_add:
      - video
      - render
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, graphics, compute, utility]
    
  app:
    
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      
    devices:
      - /dev/dri:/dev/dri

    group_add:
      - video
      - render
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, graphics, compute, utility]
