services:

  dev:
    build:
      context: .
      target: dev
    image: project_name:dev
    container_name: project_name-dev
    
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${UID:-1000}:/run/user/1000
      - .:/app
              
    network_mode: "host"
    stdin_open: true
    tty: true
    command: /bin/bash
    
  app:
    build:
      context: .
      target: app
    image: project_name:v0.0.0
    container_name: project_name-app
      
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - PKG_SCRIPT=subproject-1-app

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${UID:-1000}:/run/user/1000
      
    network_mode: "host"
